/** Short, accurate notes for well-known stars and deep-sky objects. */

export const STAR_FACTS: Record<string, string> = {
  Sirius: 'The brightest star in the night sky, just 8.6 light-years away. A white dwarf companion, Sirius B, orbits it every 50 years.',
  Canopus: 'The second-brightest star. From California it barely clears the southern horizon in winter — look due south around midnight in January.',
  Arcturus: 'An orange giant and the brightest star of the northern sky. "Arc to Arcturus" by following the curve of the Big Dipper’s handle.',
  Vega: 'A bright blue-white star in Lyra and one corner of the Summer Triangle. About 12,000 years from now it will be our pole star.',
  Capella: 'Actually two yellow giant stars orbiting each other every 104 days, high overhead on winter evenings.',
  Rigel: 'A blue supergiant marking Orion’s foot, some 120,000 times more luminous than the Sun.',
  Procyon: 'The "Little Dog Star" in Canis Minor, only 11.5 light-years away, with a white dwarf companion.',
  Betelgeuse: 'A red supergiant on Orion’s shoulder so large it would engulf Jupiter’s orbit. It will one day explode as a supernova.',
  Altair: 'One of the nearest bright stars (16.7 ly). It spins so fast — about once every 9 hours — that it bulges at its equator.',
  Aldebaran: 'The fiery orange eye of Taurus the Bull, set against the V-shaped Hyades cluster (which is actually much farther away).',
  Antares: 'The red heart of Scorpius; its name means "rival of Mars" for its colour. Low in the south on summer evenings.',
  Spica: 'A blue-white binary in Virgo whose two stars orbit each other every four days, distorting each other into egg shapes.',
  Pollux: 'The brighter of the Gemini twins, an orange giant with a confirmed exoplanet.',
  Castor: 'A remarkable sextuple star system: three pairs of stars orbiting together in Gemini.',
  Fomalhaut: 'The lonely bright star of the southern autumn sky, surrounded by a vast dusty debris disk.',
  Deneb: 'The tail of Cygnus the Swan and one of the most luminous stars known, perhaps 2,600 light-years away.',
  Regulus: 'The heart of Leo the Lion, spinning so fast it is flattened into an oblate shape.',
  Polaris: 'The North Star, sitting less than 1° from the north celestial pole. Its altitude equals your latitude — about 37.5° in Mariposa.',
  Mizar: 'The middle star of the Big Dipper’s handle. Sharp eyes can see its companion Alcor — an old test of eyesight.',
  Alcor: 'The faint companion of Mizar in the Big Dipper’s handle.',
  Algol: 'The "Demon Star" in Perseus: an eclipsing binary that fades by a factor of three every 2.87 days.',
  Mira: 'The "Wonderful" star in Cetus, a pulsating red giant that swings from naked-eye visibility to invisibility over 11 months.',
  Bellatrix: 'Orion’s left shoulder, a hot blue giant about 250 light-years away.',
  Alnilam: 'The middle star of Orion’s Belt, a blue supergiant about 2,000 light-years away.',
  Alnitak: 'The easternmost Belt star of Orion, near the Horsehead and Flame nebulae.',
  Mintaka: 'The westernmost star of Orion’s Belt, sitting almost exactly on the celestial equator.',
  Dubhe: 'One of the two "Pointer" stars of the Big Dipper that lead to Polaris.',
  Merak: 'Together with Dubhe, it points toward Polaris — extend the line about five times their separation.',
  Alkaid: 'The star at the tip of the Big Dipper’s handle.',
  Shaula: 'The stinger of Scorpius, low in the south on summer evenings from California.',
  Achernar: 'A very fast-spinning, flattened blue star — too far south to rise from Mariposa or Sacramento.',
  Hadar: 'A bright southern star in Centaurus, below the horizon from California.',
  Rigil: 'Alpha Centauri, the nearest star system to the Sun — too far south to see from California.',
  'Rigil Kentaurus': 'Alpha Centauri A, part of the nearest star system to the Sun at 4.37 light-years.',
  Mirach: 'A red giant in Andromeda — hop two stars "up" from it to find the Andromeda Galaxy.',
  Alpheratz: 'Shared corner of Andromeda and the Great Square of Pegasus.',
  Menkar: 'A red giant marking the jaw of Cetus the whale.',
  Hamal: 'The brightest star in Aries, an orange giant 66 light-years away.',
  Albireo: 'A gorgeous gold-and-blue double star at the head of Cygnus — a favourite for small telescopes.',
  Thuban: 'The pole star of the ancient Egyptians around 2800 BC, in the tail of Draco.',
  Kochab: 'One of the "Guardians of the Pole" in the Little Dipper.',
  Denebola: 'The tail of Leo the Lion.',
  Alphard: 'The solitary orange heart of Hydra, the largest constellation.',
  Sadr: 'The centre of the Northern Cross (Cygnus), deep in the summer Milky Way.',
  Enif: 'The nose of Pegasus, an orange supergiant.',
  Markab: 'A corner of the Great Square of Pegasus.',
  Nunki: 'Part of the Teapot asterism in Sagittarius, toward the centre of our galaxy.',
  'Kaus Australis': 'The brightest star of the Sagittarius Teapot.',
  Alioth: 'The brightest star in Ursa Major, in the Big Dipper’s handle.',
  Elnath: 'The tip of Taurus’ northern horn, shared historically with Auriga.',
  Adhara: 'A blue giant in Canis Major, once the brightest star in the sky about 4.7 million years ago.',
  Wezen: 'A yellow-white supergiant in Canis Major.',
  Saiph: 'Orion’s right knee, a blue supergiant.',
};

export const DSO_FACTS: Record<string, string> = {
  'M 31': 'The Andromeda Galaxy — 2.5 million light-years away and the most distant thing most people can see without optics. A smudge several Moons wide from dark sites like Mariposa.',
  'M 42': 'The Orion Nebula, a stellar nursery 1,350 light-years away in Orion’s Sword. Visible to the naked eye as a fuzzy "star".',
  'M 45': 'The Pleiades (Seven Sisters), a young cluster of hot blue stars 444 light-years away. Most people can count six or seven.',
  'M 44': 'The Beehive Cluster (Praesepe) in Cancer — a hazy patch to the eye, a swarm of stars in binoculars.',
  'M 13': 'The Great Globular Cluster in Hercules: a ball of ~300,000 stars, 22,000 light-years away.',
  'M 8': 'The Lagoon Nebula in Sagittarius, visible to the naked eye in dark summer skies.',
  'M 57': 'The Ring Nebula, the glowing shell cast off by a dying Sun-like star.',
  'M 27': 'The Dumbbell Nebula, one of the brightest planetary nebulae.',
  'M 1': 'The Crab Nebula, the remnant of a supernova recorded by Chinese astronomers in 1054.',
  'M 51': 'The Whirlpool Galaxy, a face-on spiral interacting with a companion.',
  'M 81': 'Bode’s Galaxy, a bright spiral in Ursa Major.',
  'M 82': 'The Cigar Galaxy, bursting with star formation.',
  'M 33': 'The Triangulum Galaxy — a faint, large spiral; a real challenge to the naked eye even from dark sites.',
  'M 22': 'A bright globular cluster in Sagittarius, one of the nearest to Earth.',
  'M 7': 'Ptolemy’s Cluster, a bright open cluster near the tail of Scorpius.',
  'M 6': 'The Butterfly Cluster near Scorpius’ stinger.',
  'M 11': 'The Wild Duck Cluster, one of the richest open clusters.',
  'M 16': 'The Eagle Nebula, home of the "Pillars of Creation".',
  'M 17': 'The Omega (Swan) Nebula in Sagittarius.',
  'M 20': 'The Trifid Nebula, split by dark dust lanes.',
  'M 24': 'The Sagittarius Star Cloud, a window through the dust toward the galactic centre.',
  'M 101': 'The Pinwheel Galaxy, a large face-on spiral.',
  'M 104': 'The Sombrero Galaxy, seen almost edge-on with a prominent dust lane.',
  'M 3': 'A rich globular cluster in Canes Venatici.',
  'M 5': 'One of the oldest globular clusters in the Milky Way.',
  'M 35': 'A large open cluster at the feet of Gemini.',
  'M 36': 'An open cluster in Auriga (the Pinwheel Cluster).',
  'M 37': 'The richest of Auriga’s three bright open clusters.',
  'M 38': 'The Starfish Cluster in Auriga.',
  'M 41': 'A bright open cluster just south of Sirius.',
  'M 47': 'A bright, scattered open cluster in Puppis.',
  'M 92': 'A bright globular cluster in Hercules, often overlooked next to M13.',
  'M 15': 'A dense globular cluster in Pegasus with a collapsed core.',
  'M 2': 'A large globular cluster in Aquarius.',
  'M 4': 'The nearest globular cluster, next to Antares.',
  'M 34': 'An open cluster in Perseus, nice in binoculars.',
  'M 39': 'A loose open cluster in Cygnus.',
  'M 46': 'An open cluster in Puppis with a planetary nebula superimposed.',
  'M 64': 'The Black Eye Galaxy, with a dark dust band across its core.',
  'M 97': 'The Owl Nebula, a planetary nebula in Ursa Major.',
  'M 78': 'A reflection nebula in Orion.',
  'M 43': 'De Mairan’s Nebula, part of the Orion Nebula complex.',
  'M 40': 'Winnecke 4, a double star Messier catalogued by mistake.',
  'M 110': 'A satellite galaxy of Andromeda.',
  'M 32': 'A compact satellite galaxy of Andromeda.',
  'NGC 869': 'h Persei, half of the stunning Double Cluster.',
  'NGC 884': 'χ Persei, half of the Double Cluster.',
  'C 14': 'The Double Cluster in Perseus — two rich star clusters side by side, beautiful in binoculars.',
  'NGC 7000': 'The North America Nebula near Deneb, shaped like the continent.',
  'NGC 253': 'The Sculptor Galaxy, a bright, dusty edge-on spiral.',
  'NGC 7293': 'The Helix Nebula, one of the closest planetary nebulae.',
};

export const CONSTELLATION_FACTS: Record<string, string> = {
  Ori: 'The Hunter — the most recognisable winter constellation, with Betelgeuse, Rigel, the Belt and the Orion Nebula.',
  UMa: 'The Great Bear, containing the Big Dipper asterism — the key to finding Polaris and Arcturus.',
  UMi: 'The Little Bear. Polaris marks the end of the Little Dipper’s handle.',
  Cas: 'The W-shaped Queen, opposite the Big Dipper around Polaris.',
  Sco: 'The Scorpion, low in California’s summer south, with red Antares at its heart.',
  Sgr: 'The Archer, whose Teapot asterism points toward the centre of the Milky Way.',
  Cyg: 'The Swan (Northern Cross), flying down the Milky Way in summer and autumn.',
  Lyr: 'The Lyre, small but home to Vega and the Ring Nebula.',
  Leo: 'The Lion — look for the backwards question mark (the Sickle) in spring.',
  Tau: 'The Bull, with Aldebaran, the Hyades and the Pleiades.',
  Gem: 'The Twins, Castor and Pollux, high on winter evenings.',
  CMa: 'The Great Dog, home of Sirius.',
  And: 'Andromeda, the chained princess — and the direction of the Andromeda Galaxy.',
  Peg: 'The winged horse, marked by the Great Square in autumn.',
  Per: 'The hero Perseus, with the Double Cluster and the eclipsing star Algol. Radiant of the August Perseids.',
  Aql: 'The Eagle, with Altair in the Summer Triangle.',
  Boo: 'The Herdsman, shaped like a kite, anchored by Arcturus.',
  Vir: 'The Maiden, the largest zodiac constellation, rich in galaxies.',
  Aur: 'The Charioteer, with Capella and three bright open clusters.',
  Dra: 'The Dragon, winding between the Big and Little Dippers.',
  Her: 'Hercules, with the Keystone asterism and the great globular cluster M13.',
  Cen: 'The Centaur. Only its northern part rises from California.',
  Cru: 'The Southern Cross — below the horizon from California.',
};
